frontend:
  assets:
    etag: false
    expires: ~
    cache-control:
      default:
        max-age: 29030401

    directories:
      - assets/
      - data/mediapool/
      - data/dyn/public/
      - sally/backend/assets/
      - sally/setup/assets/
      - sally/noir/assets/

    rewrites:
      - { pattern: '#^assets/addon/([^/.]+)/([^/.]+)/(.+?)$#', replacement: 'sally/addons/$1/$2/assets/$3' }
      - { pattern: '#^assets/app/([^/.]+)/(.+?)$#',            replacement: 'sally/$1/assets/$2'           }
